name: LeetCode Reminder

on:
  schedule:
  - cron: '0 0,18 * * *'
  workflow_dispatch:

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    environment: EmailReminder
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Check Environment Vars
        run: |
          echo "SENDER_REMINDER length: ${#SENDER_REMINDER}"
          echo "PASSWORD_REMINDER length: ${#PASSWORD_REMINDER}"
          echo "RECIPIENTS_REMINDER length: ${#RECIPIENTS_REMINDER}"

      - name: Run Reminder Script
        env:
          SENDER_REMINDER: ${{ secrets.SENDER_REMINDER }}
          PASSWORD_REMINDER: ${{ secrets.PASSWORD_REMINDER }}
          RECIPIENTS_REMINDER: ${{ secrets.RECIPIENTS_REMINDER }}
        run: python utils/reminder.py
