name: LeetCode Reminder

on:
  schedule:
  - cron: '0 0,18 * * *'
  workflow_dispatch:

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    environment: EmailReminder
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Run Reminder Script
        env:
          SENDER_REMINDER: ${{ vars.SENDER_REMINDER }}
          PASSWORD_REMINDER: ${{ vars.PASSWORD_REMINDER }}
          RECIPIENTS_REMINDER: ${{ vars.RECIPIENTS_REMINDER }}

        run: |
          echo "SENDER_REMINDER length: ${#SENDER_REMINDER}"
          echo "PASSWORD_REMINDER length: ${#PASSWORD_REMINDER}"
          echo "RECIPIENTS_REMINDER length: ${#RECIPIENTS_REMINDER}"
          python utils/reminder.py
