name: Weekly Summary

on: 
  push:
    branches: [master, main]
  workflow_dispatch:

jobs:
  weekly_summary:
    runs-on: ubuntu-latest
    environment: WeeklySummary
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: python -m pip install google-genai
      - name: Test Env
        env:
          KEY_SUMMARY: ${{vars.KEY_SUMMARY}}
          GIT_SHA: ${{github.sha}}
          SENDER: ${{vars.SENDER}}
          PASSWORD_EMAIL: ${{vars.PASSWORD_EMAIL}}
        run: |
          echo "KEY_SUMMARY length: ${#KEY_SUMMARY}"
          echo "GIT_SHA length: ${#GIT_SHA}"
          echo "SENDER length: ${#SENDER}"
          echo "PASSWORD_EMAIL length: ${#PASSWORD_EMAIL}"
      - name: Run Code
        run: python utils/wksm.py
        
