name: Weekly Summary

on: push
  cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  weekly_summary:
    runs-on: ubuntu-latest
    environment: WeeklySummary
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: python -m pip install google-genai
      - name: Test Env
        env:
          KEY_SUMMARY: ${{vars.KEY_SUMAARY}}
          GIT_SHA: ${{vars.GIT_SHA}}
        run: |
          echo "KEY_SUMMARY length: ${#KEY_SUMMARY}"
          echo "GIT_SHA length: ${#GIT_SHA}"
      - name: Run Code
          python utils/wksm.py
        
